-- 插入用户
INSERT INTO T_FRAME_USER VALUES(HSEQ_USER.NEXTVAL,'ROOT','ROOT');
INSERT INTO T_FRAME_USER VALUES(HSEQ_USER.NEXTVAL,'ADMIN','ADMIN');
INSERT INTO T_FRAME_USER VALUES(HSEQ_USER.NEXTVAL,'USER','USER');
INSERT INTO T_FRAME_USER VALUES(HSEQ_USER.NEXTVAL,'GUEST','GUEST');
-- 插入角色
INSERT INTO T_FRAME_ROLE VALUES(HSEQ_ROLE.NEXTVAL,'ROOT');
INSERT INTO T_FRAME_ROLE VALUES(HSEQ_ROLE.NEXTVAL,'ADMIN');
INSERT INTO T_FRAME_ROLE VALUES(HSEQ_ROLE.NEXTVAL,'USER');
INSERT INTO T_FRAME_ROLE VALUES(HSEQ_ROLE.NEXTVAL,'GUEST');
-- 插入权限
INSERT INTO T_FRAME_PERMISSION VALUES(HSEQ_PERMISSION.NEXTVAL,'USER');
INSERT INTO T_FRAME_PERMISSION VALUES(HSEQ_PERMISSION.NEXTVAL,'MENU');
INSERT INTO T_FRAME_PERMISSION VALUES(HSEQ_PERMISSION.NEXTVAL,'*');